### ISSUE TITLE
Error in wonderapi::getData

### ISSUE THREAD

**Issue by Diego-Yizhi** [socdataR/wonderapi#19]
It seems that the "D66" database is inaccessible.
![error](https://raw.githubusercontent.com/Diego-Yizhi/images/main/20230113155912.png)

**Comment by jtr13** [comment]
See my comment here: https://github.com/socdataR/wonderapi/issues/20

**Comment by jtr13** [comment]
This should work now thanks to https://github.com/socdataR/wonderapi/pull/21 from @brendensm
