### ISSUE TITLE
Fail to build vignettes

### ISSUE THREAD

**Issue by Diego-Yizhi** [socdataR/wonderapi#20]
Thanks for your contribution! 
When I try to install the package and build the vignettes, it shows
![error_vig](https://raw.githubusercontent.com/Diego-Yizhi/images/main/20230113161505.png)

**Comment by jtr13** [comment]
Sorry, the API keeps changing so code that previously worked doesn't work any more. I wish I had time to devote to this now but I'm busy prepping for a new course I'm teaching spring semester. Your best bet is to use the Wonder web interface https://wonder.cdc.gov/ or full data files of some of the data sets such as mortality and birth data from https://www.nber.org/research/data

**Comment by klittle314** [comment]
Thanks jtr13 for contributing the package.   I have the same problem as Diego-Yizhi, the Rmd code lines 140-144 certainly looks unremarkable!  I loaded the package without the vignettes using build_vignettes = FALSE in the install_github call.   I am trying to get a bunch of tables from CDC WONDER  and am interested in trying your package.

**Comment by jtr13** [comment]
Thanks for letting me know about these issues. It's hard to keep the default query list https://github.com/socdataR/wonderapi/blob/master/data-raw/D66_Defaults.xml up to date since the documentation isn't good (among other reasons, like time!). It looks like Detailed Mortality D76 is working:

```
> head(getData("D76"))
# A tibble: 6 × 4
  Year   Deaths Population `Crude Rate`
  <chr>   <dbl>      <dbl>        <dbl>
1 1999  2391043  279040168         857.
2 2000  2402995  281421906         854.
3 2001  2416003  284968955         848.
4 2002  2443030  287625193         849.
5 2003  2447946  290107933         844.
6 2004  2397269  292805298         819.
```

**Comment by jtr13** [comment]
This should work now thanks to https://github.com/socdataR/wonderapi/pull/21 from @brendensm
