### ISSUE TITLE
Unable to Use Locations in D76

### ISSUE THREAD

**Issue by CIOData** [socdataR/wonderapi#24]
I am attempting to make a pull from table D76 that includes restrictions on the location by county. These include selections to the F parameter F_D76.V9. When I run `send_query()` for this I get the following error:

```
Message from query:
Selections were made to location variable D76.V9.
Error in send_query("D76", "Underlying Cause of Death, 1999-2020_1721649898996-req.xml") : 
  Internal Server Error (HTTP 500).
```
Please advise.

**Comment by jtr13** [comment]
Thanks for letting me know. The CDC makes a lot of changes and it's hard to keep up with them. @brendensm no pressure but if you get a chance could you see what's going on here? Thanks!

**Comment by brendensm** [comment]
@CIOData Restrictions based on location are not allowed by the API. 

From the README:
> NOTE, HOWEVER, THAT THE CDC DOES NOT ALLOW QUERIES WITH LOCATION FIELDS THROUGH THE API. If you wish to limit or group results by Region, Division, State or County, or Urbanization, use the [CDC Wonder](https://wonder.cdc.gov/) web interface rather than the API – either with or without this package. For more information on this limitation, see: https://wonder.cdc.gov/wonder/help/WONDER-API.html.

**Comment by CIOData** [comment]
Thank you for looking into this. That's frustrating, but not the first time I've encountered the CDC putting up additional barriers to automating data gathering.

-Todd
________________________________

**Comment by jtr13** [comment]
Agree, it's frustrating especially since those variables are available on the CDC WONDER web interface.
